Fix for Issue #4
ghost1face/base62 pull request #10
Opened 2022-08-26 22:16 UTC by DJGosnell

Addresses #4 issue with byte arrays which start with 0.  The following items are changed:
 - Base62Converter.BaseConvert() is now public.
 - Base62Converter.BaseConvert() now will prepend zero bytes to the beginning of the returned byte array.

2022-09-07 02:17 UTC, ghost1face requested changes
Thanks for taking the time to contribute!  I've got a few notes I added below

2022-09-07 02:17 UTC, ghost1face commented on Base62/Base62Converter.cs
> +                throw new ArgumentOutOfRangeException(nameof(targetBase), targetBase, "Value must be between 0 & 257");
```suggestion
                throw new ArgumentOutOfRangeException(nameof(targetBase), targetBase, "Value must be between 0 & 256");
```

2022-09-07 02:17 UTC, ghost1face commented on Base62/Base62Converter.cs
> +                throw new ArgumentOutOfRangeException(nameof(sourceBase), sourceBase, "Value must be between 0 & 257");
```suggestion
                throw new ArgumentOutOfRangeException(nameof(sourceBase), sourceBase, "Value must be between 0 & 256");
```

2022-09-07 02:17 UTC, ghost1face commented on Base62/Base62Converter.cs
> +        public static byte[] BaseConvert(byte[] source, int sourceBase, int targetBase)
Considering this is only for Base62 and not others, I'd rather keep this `private`.  For the sake of unit tests we can make `internal` and expose the internals to the test project

2022-09-07 02:17 UTC, ghost1face commented on Base62/Base62Converter.cs
> +                quotient.Clear();
👍🏾

2022-09-07 13:00 UTC, DJGosnell commented on Base62/Base62Converter.cs
> +                throw new ArgumentOutOfRangeException(nameof(targetBase), targetBase, "Value must be between 0 & 257");
I was thinking about the confusion between exclusive and inclusive here but I failed to write an accurate enough exception text.  What about this: ```Value must be between 1 & 256 (inclusive)```

2022-09-07 13:06 UTC, ghost1face commented on Base62/Base62Converter.cs
> +                throw new ArgumentOutOfRangeException(nameof(targetBase), targetBase, "Value must be between 0 & 257");
I like that better, let's go that route

2022-09-07 13:07 UTC, ghost1face commented
I'll have to get these actions working again, all tests pass

2022-09-07 14:10 UTC, DJGosnell commented on Base62/Base62Converter.cs
> +        public static byte[] BaseConvert(byte[] source, int sourceBase, int targetBase)
Understand this concern as it exposes additional required test coverage.  Can we make it protected internal at least as I would like to be able to call this method from a derived class.  I have a workflow which looks like this. Base64 String -> byte[] -> Base62 String.
If I lose the access to this method, then I have to Base64 String -> byte[] -> UTF8 Encode String -> UTF8 Decode String -> Base62 String which just adds extra work in some hot paths I have.

2022-09-07 14:17 UTC, DJGosnell commented on Base62/Base62Converter.cs
> +        public static byte[] BaseConvert(byte[] source, int sourceBase, int targetBase)
I take this back.  I was thinking about an old workflow.  I will change it to internal only.

2022-09-14 16:36 UTC, ghost1face approved these changes

2022-09-14 16:38 UTC, ghost1face commented
Thanks for the update, I'll get this in after some cleanup on my end

2022-09-14 16:38 UTC, merged